target-version = "py311"
line-length = 120

[lint]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "SIM101",
    "SIM103",
    "SIM117",
    "PLW1510",
    "UP022",
    "PYI034",
    "ISC004",
    "RUF009",
    "RUF046",
    "PIE810",
    "DTZ007",
    "EXE001",
]
