#!/usr/bin/env bash
# Quality gates for the hand-maintained and generated native sources in the
# experimental Tree-sitter yt-sql package. Generated sources are compiled but
# are deliberately never reformatted or subjected to stylistic clang-tidy rules.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXPERIMENT_DIR="$ROOT_DIR/experiments/tree-sitter-yt-sql"

MAINTAINED_FORMAT_SOURCES=(
    "$EXPERIMENT_DIR/bindings/c/tree_sitter/tree-sitter-yt-sql.h"
    "$EXPERIMENT_DIR/bindings/python/tree_sitter_yt_sql/binding.c"
)
MAINTAINED_TIDY_SOURCES=(
    "$EXPERIMENT_DIR/bindings/python/tree_sitter_yt_sql/binding.c"
)
GENERATED_C_SOURCES=(
    "$EXPERIMENT_DIR/src/parser.c"
)

# An external scanner, if introduced by a later grammar revision, is maintained
# by this project rather than generated by Tree-sitter.
if [[ -f "$EXPERIMENT_DIR/src/scanner.c" ]]; then
    MAINTAINED_FORMAT_SOURCES+=("$EXPERIMENT_DIR/src/scanner.c")
    MAINTAINED_TIDY_SOURCES+=("$EXPERIMENT_DIR/src/scanner.c")
fi

usage() {
    cat <<'USAGE'
Usage: scripts/lint-tree-sitter.sh [--format|--check-format|--lint|--check-generated|--check]

  --format          Format hand-maintained C/C++ sources in place.
  --check-format    Check formatting without modifying files.
  --lint            Run clang-tidy on hand-maintained native sources.
  --check-generated Compile-check generated Tree-sitter C without rewriting it.
  --check           Run format, lint and generated-source checks (default).
USAGE
}

require_tool() {
    if ! command -v "$1" >/dev/null 2>&1; then
        printf 'error: required tool not found: %s\n' "$1" >&2
        exit 127
    fi
}

python_include_dir() {
    python - <<'PY'
import sysconfig
print(sysconfig.get_path("include"))
PY
}

check_format() {
    require_tool clang-format
    clang-format --dry-run --Werror "${MAINTAINED_FORMAT_SOURCES[@]}"
}

format_sources() {
    require_tool clang-format
    clang-format -i "${MAINTAINED_FORMAT_SOURCES[@]}"
}

lint_sources() {
    require_tool clang-tidy
    require_tool python
    local python_include
    python_include="$(python_include_dir)"

    local source
    for source in "${MAINTAINED_TIDY_SOURCES[@]}"; do
        clang-tidy "$source" -- \
            -std=c11 \
            -I"$python_include" \
            -I"$EXPERIMENT_DIR/src"
    done
}

check_generated() {
    require_tool clang
    local source
    for source in "${GENERATED_C_SOURCES[@]}"; do
        clang -std=c11 -Wall -Wextra -Wpedantic -Werror \
            -I"$EXPERIMENT_DIR/src" -fsyntax-only "$source"
    done
}

mode="${1:---check}"
case "$mode" in
    --format)
        format_sources
        ;;
    --check-format)
        check_format
        ;;
    --lint)
        lint_sources
        ;;
    --check-generated)
        check_generated
        ;;
    --check)
        check_format
        lint_sources
        check_generated
        ;;
    -h|--help)
        usage
        ;;
    *)
        usage >&2
        exit 2
        ;;
esac
